name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: abernicchia-heroku/heroku-sources-endpoint-deploy-action@main
        with:
          heroku-api-key: ${{secrets.HEROKU_API_KEY}}
          heroku-app-name: ab-ps-ghactions-stage # "YOUR APP's NAME" must be unique in Heroku
      # - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: ab-ps-ghactions-stage # "YOUR APP's NAME" must be unique in Heroku
      #     heroku_email: ${{secrets.HEROKU_API_USER}} # "YOUR EMAIL"
